apiVersion: v1
kind: Service
metadata:
  name: pubsub-emulator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pubsub-emulator
  ports:
    - name: pubsub
      port: {{ .Values.service.port }}
      targetPort: 8085