apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hool-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: quay.io/minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              mc alias set local http://minio:{{ .Values.service.apiPort }} \
               {{ .Values.credentials.rootUser }} {{ .Values.credentials.rootPassword }} && \
              mc mb --ignore-existing minio/{{ .Values.bucket }}