---
# Source: trips/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trips
  namespace: trip-manager-staging
  labels: 
    app.kubernetes.io/name: trips
    app.kubernetes.io/instance: trips
    app.kubernetes.io/version: "sha-0e286a04d815dbfa24ed6851383b9e76713d4dc5"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: trips-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com
