apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      name: gcp-secret-store
      projectID: {{ .Values.gcp.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.gcp.region }}
          clusterName: {{ .Values.gcp.clusterName }}
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets