replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: PORT
    value: "8087"
  - name: LOG_LEVEL
    value: "info"
  - name: REDIS_URL
    value: "redis://redis-master.trip-manager-prod.svc.cluster.local:6379"
  - name: API_URL
    value: "https://www.auswaertiges-amt.de/opendata/travelwarning"
  - name: CORS_ALLOWED_ORIGINS
    value: "https://neatnode.xyz,https://www.neatnode.xyz"

serviceAccount:
  gcpServiceAccount: "travel-warning-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com"