postgres:
  password: ""

persistence:
  enabled: true
  size: 8Gi
  storageClass: premium-rwo

externalSecrets:
  enabled: true
  secrets:
    - secretKey: POSTGRES_PASSWORD
      remoteKey: trips-postgres-password