image:
  repository: postgres
  tag: "16-alpine"
replicaCount: 1
postgres:
  db: trips
  user: trips
  password: placeholder
service:
  port: 5432
persistence:
  enabled: false
externalSecrets:
  enabled: true
  secrets:
    - secretKey: POSTGRES_PASSWORD
      remoteKey: trips-database-password
