apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector-sa
      containers:
        - name: otel-collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["--config=/conf/config.yaml"]
          ports:
            - containerPort: 4317
              name: grpc
            - containerPort: 4318
              name: http
            - containerPort: 8889
              name: prometheus
          volumeMounts:
            - name: config
              mountPath: /conf
          resources: {{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: otel-collector-config