apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "otel-collector-sa@{{ .Values.gcpProjectID }}.iam.gserviceaccount.com"