---
# Source: feed-generator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-generator
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: feed-generator
    app.kubernetes.io/instance: feed-generator
    app.kubernetes.io/version: "dev"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: feed-generator
      app.kubernetes.io/instance: feed-generator
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: feed-generator
        app.kubernetes.io/instance: feed-generator
      annotations:
        checksum/config: df6ea2fc841a67d5fb58767713a34ae88b200fcb966ee1f3509731bcc152b03b
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: feed-generator
          image: "europe-west1-docker.pkg.dev/project-32c60644-299b-4b05-8cf/trip-manager/backend/feed-generator:dev"
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
              name: http
              protocol: TCP
          env: 
            - name: PORT
              value: "8090"
            - name: GCP_PROJECT_ID
              value: project-32c60644-299b-4b05-8cf
            - name: PUBSUB_SUBSCRIPTION_ID
              value: trip-events-sub
          envFrom: 
            - secretRef:
                name: feed-generator-secrets
          resources: 
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      serviceAccountName: feed-generator
