---
# Source: social/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: social
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: social
    app.kubernetes.io/instance: social
    app.kubernetes.io/version: "sha-7befcfa53aeb6d8c53151b1975df2d4dfdf98b21"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: social-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com
