apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trips-postgres-bali-secret
  namespace: trip-manager-bali
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: trips-postgres-bali-secret
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: enterprise-bali-db-password
