replicaCount: 1

service:
  healthPath: /health

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

hpa:
  enabled: false

env:
  - name: PORT
    value: "8083"
  - name: LOG_LEVEL
    value: "info"
  - name: AUTH_SERVICE_URL
    value: "http://auth.trip-manager-prod.svc.cluster.local:8082"
  - name: STORAGE_BUCKET_URL
    value: "https://storage.googleapis.com/trip-manager-bucket"

externalSecrets:
  enabled: true
  secrets:
    - secretKey: DATABASE_URL
      remoteKey: users-database-url

envFrom:
  - secretRef:
      name: users-secrets

serviceAccount:
  gcpServiceAccount: "users-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com"