replicaCount: 1

service:
  healthPath: /health

probes:
  liveness: ""
  readiness: ""

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

hpa:
  enabled: false

env:
  - name: PORT
    value: "8090"
  - name: GCP_PROJECT_ID
    value: "trip-manager-local"
  - name: PUBSUB_SUBSCRIPTION_ID
    value: "feed-generator-trip-created,feed-generator-trip-liked,feed-generator-trip-commented"
  - name: PUBSUB_EMULATOR_HOST
    value: "pubsub-emulator.trip-manager-dev.svc.cluster.local:8085"
  - name: NEO4J_URI
    value: "bolt://neo4j.trip-manager-dev.svc.cluster.local:7687"
  - name: NEO4J_USERNAME
    value: "neo4j"
  - name: NEO4J_PASSWORD
    value: "neo4jpassword"
  - name: LOG_LEVEL
    value: "debug"