image:
  pullPolicy: Always

service:
  healthPath: /health

env:
  - name: PORT
    value: "8090"
  - name: GCP_PROJECT_ID
    value: "project-32c60644-299b-4b05-8cf"
  - name: PUBSUB_SUBSCRIPTION_ID
    value: "trip-events-sub"

externalSecrets:
  enabled: true
  secrets:
    - secretKey: NEO4J_URI
      remoteKey: neo4j-url
    - secretKey: NEO4J_USERNAME
      remoteKey: neo4j-username
    - secretKey: NEO4J_PASSWORD
      remoteKey: neo4j-password

envFrom:
  - secretRef:
      name: feed-generator-secrets

serviceAccount:
  gcpServiceAccount: "feed-generator-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com"