---
# Source: users/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: users
  namespace: trip-manager-staging
  labels: 
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: users
    app.kubernetes.io/version: "sha-8af5008f1487946b9e0751c0ed11a1d7022c40fc"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: users-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com
