image:
  pullPolicy: Never

replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

hpa:
  enabled: false

env:
  - name: PORT
    value: "8085"
  - name: LOG_LEVEL
    value: "debug"
  - name: STORAGE_PROVIDER
    value: "s3"
  - name: S3_ENDPOINT
    value: "http://minio.trip-manager-dev.svc.cluster.local:9000"
  - name: S3_PUBLIC_URL
    value: "http://192.168.49.2:30900"
  - name: STORAGE_BUCKET
    value: "trip-manager"
  - name: S3_REGION
    value: "us-east-1"
  - name: S3_ACCESS_KEY
    value: "minioadmin"
  - name: S3_SECRET_KEY
    value: "minioadmin"
  - name: S3_USE_SSL
    value: "false"
  - name: AUTH_SERVICE_URL
    value: "http://auth.trip-manager-dev.svc.cluster.local:8082"
  - name: CORS_ALLOWED_ORIGINS
    value: "http://localhost:3000"
  - name: OTEL_COLLECTOR_ENDPOINT
    value: "otel-collector.trip-manager-dev.svc.cluster.local:4317"