---
# Source: locations/templates/externalsecrets.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: locations-secrets
  namespace: trip-manager-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: locations-secrets
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: locations-database-url

