---
# Source: locations/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: locations
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: locations
    app.kubernetes.io/instance: locations
    app.kubernetes.io/version: "dev"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    cloud.google.com/backend-config: "{\"default\": \"locations-backend-config\"}"
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: locations
    app.kubernetes.io/instance: locations
---
# Source: locations/templates/service.yaml
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: locations-hc-policy
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: locations
    app.kubernetes.io/instance: locations
    app.kubernetes.io/version: "dev"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8086
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: locations

