---
# Source: locations/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: locations
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: locations
    app.kubernetes.io/instance: locations
    app.kubernetes.io/version: "dev"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: locations-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com

