postgres:
  password: ""

persistence:
  enabled: true
  size: 8Gi
  storageClass: standard-rwo

externalSecrets:
  enabled: true
  secrets:
    - secretKey: POSTGRES_PASSWORD
      remoteKey: newsletter-database-password