DO $$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'newsletter_app') THEN
        EXECUTE format('CREATE USER newsletter_app WITH PASSWORD %L', '{{APP_DB_PASSWORD}}');
    END IF;
END $$;
GRANT CONNECT ON DATABASE newsletter TO newsletter_app;
GRANT USAGE ON SCHEMA public TO newsletter_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO newsletter_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO newsletter_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO newsletter_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO newsletter_app;