DO $$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'trips_app') THEN
            EXECUTE format('CREATE USER trips_app WITH PASSWORD %L', current_setting('app.db_password', true));
        END IF;
    END $$;

GRANT CONNECT ON DATABASE trips TO trips_app;
GRANT USAGE ON SCHEMA public TO trips_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO trips_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO trips_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO trips_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO trips_app;

ALTER TABLE trips FORCE ROW LEVEL SECURITY;
ALTER TABLE locations FORCE ROW LEVEL SECURITY;
ALTER TABLE location_images FORCE ROW LEVEL SECURITY;
ALTER TABLE transports FORCE ROW LEVEL SECURITY;
ALTER TABLE accommodations FORCE ROW LEVEL SECURITY;