---
# Source: travel-warning/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: travel-info
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: travel-warning
    app.kubernetes.io/instance: travel-info
    app.kubernetes.io/version: "dev"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: travel-info-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com

