---
# Source: travel-warning/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-warning
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: travel-warning
    app.kubernetes.io/instance: travel-warning
    app.kubernetes.io/version: "dev"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: travel-warning
      app.kubernetes.io/instance: travel-warning
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: travel-warning
        app.kubernetes.io/instance: travel-warning
      annotations:
        checksum/config: f6b91b7c4eef11760c6249a2424c407dce7fbd50775dbcf9c97e005f88bb11fc
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: travel-warning
          image: "europe-west1-docker.pkg.dev/project-32c60644-299b-4b05-8cf/trip-manager/backend/travel-warning:dev"
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
              name: http
              protocol: TCP
          env: 
            - name: PORT
              value: "8087"
            - name: LOG_LEVEL
              value: info
            - name: API_URL
              value: https://www.auswaertiges-amt.de/opendata/travelwarning
            - name: CORS_ALLOWED_ORIGINS
              value: https://neatnode.xyz,https://www.neatnode.xyz
            - name: OTEL_COLLECTOR_ENDPOINT
              value: otel-collector.trip-manager-prod.svc.cluster.local:4317
            - name: AUTH_SERVICE_URL
              value: http://auth.trip-manager-prod.svc.cluster.local:8082
          envFrom: 
            - secretRef:
                name: travel-warning-secrets
          resources: 
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      serviceAccountName: travel-warning
