---
# Source: travel-warning/templates/externalsecrets.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: travel-warning-secrets
  namespace: trip-manager-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: travel-warning-secrets
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: redis-url

