---
# Source: frontend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: trip-manager-staging
  labels: 
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/version: "sha-984d9f2088cec93dbf53faff48b837230d202eeb"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
