image:
  repository: postgres
  tag: "16-alpine"
replicaCount: 1
postgres:
  db: users
  user: users
  password: placeholder
service:
  port: 5432
persistence:
  enabled: false
externalSecrets:
  enabled: true
  secrets:
    - secretKey: POSTGRES_PASSWORD
      remoteKey: users-database-password
