---
# Source: weather-info/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-info
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: weather-info
    app.kubernetes.io/instance: weather-info
    app.kubernetes.io/version: "dev"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: weather-info-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com

