---
# Source: auth/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  namespace: trip-manager-staging
  labels: 
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: auth
    app.kubernetes.io/version: "sha-0343f559fc152d65502551770f96616188778685"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: auth-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com
