---
# Source: newsletter-worker/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newsletter-worker
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: newsletter-worker
    app.kubernetes.io/instance: newsletter-worker
    app.kubernetes.io/version: "dev"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: newsletter-worker-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com

