image:
  pullPolicy: Never

replicaCount: 1

resources:
  requests:
    cpu: 30m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

hpa:
  enabled: false

externalSecrets:
  enabled: false
  secrets: []

env:
  - name: PORT
    value: "8070"
  - name: LOG_LEVEL
    value: "debug"
  - name: AUTH_SERVICE_URL
    value: "http://auth.trip-manager-dev.svc.cluster.local:8082"
  - name: MIGRATION_URL
    value: "postgres://newsletter:newsletter@newsletter-postgres.trip-manager-dev.svc.cluster.local:5432/newsletter?sslmode=disable"
  - name: DATABASE_URL
    value: "postgres://newsletter_app:newsletter@newsletter-postgres.trip-manager-dev.svc.cluster.local:5432/newsletter?sslmode=disable"
  - name: APP_DB_PASSWORD
    value: "newsletter"
  - name: USERS_DB_URL
    value: "postgres://users:users@users-postgres.trip-manager-dev.svc.cluster.local:5432/users?sslmode=disable"
  - name: NEO4J_URI
    value: "bolt://neo4j.trip-manager-dev.svc.cluster.local:7687"
  - name: NEO4J_USERNAME
    value: "neo4j"
  - name: NEO4J_PASSWORD
    value: "neo4jpassword"
  - name: CRON_SCHEDULE
    value: "0 */12 * * *" # Im Dev-System z.B. alle 12 Stunden
  - name: CORS_ALLOWED_ORIGINS
    value: "http://localhost:3000"
  - name: OTEL_COLLECTOR_ENDPOINT
    value: "otel-collector.trip-manager-dev.svc.cluster.local:4317"

serviceAccount:
  gcpServiceAccount: ""