apiVersion: batch/v1
kind: CronJob
metadata:
  name: newsletter-worker
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "common.fullname" . }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          containers:
            - name: worker
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["/bin/worker"]
              {{- with .Values.env }}
              env: {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.envFrom }}
              envFrom: {{ toYaml . | nindent 16 }}
              {{- end }}
              resources: {{ toYaml .Values.resources | nindent 16 }}