---
# Source: newsletter-postgres/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: newsletter-postgres
  namespace: trip-manager-staging
spec:
  serviceName: newsletter-postgres
  replicas: 1
  selector:
    matchLabels:
      app: newsletter-postgres
  template:
    metadata:
      labels:
        app: newsletter-postgres
    spec:
      containers:
        - name: newsletter-postgres
          image: "postgres:16-alpine"
          env:
            - name: POSTGRES_DB
              value: $(echo $svc | sed 's/-postgres//')
            - name: POSTGRES_USER
              value: $(echo $svc | sed 's/-postgres//')
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: newsletter-postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
      volumes:
        - name: data
          emptyDir: { }
