replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

hpa:
  enabled: false

env:
  - name: PORT
    value: "8084"
  - name: LOG_LEVEL
    value: "info"
  - name: AUTH_SERVICE_URL
    value: "http://auth.trip-manager-dev.svc.cluster.local:8082"
  - name: DATABASE_URL
    value: "postgres://trips:trips@trips-postgres.trip-manager-dev.svc.cluster.local:5432/trips?sslmode=disable"
  - name: USERS_SERVICE_URL
    value: "http://users.trip-manager-dev.svc.cluster.local:8083"
