apiVersion: v1
kind: Service
metadata:
  name: newsletter-postgres
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: newsletter-postgres
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: newsletter-postgres-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None   # Headless
  selector:
    app: newsletter-postgres
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432