#!/bin/bash

# Generate .env file from environment variables
# Used by GitHub Actions during deployment

set -e

ENV_FILE="${1:-.env}"

cat > "$ENV_FILE" << 'EOF'
# Deployment Environment Variables (Auto-generated by GitHub Actions)

# Docker Registry
GHCR_USERNAME=${GHCR_USERNAME}
GHCR_PAT=${GHCR_PAT}

# Database
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}

# JWT
JWT_SECRET=${JWT_SECRET}

# Domain (duck.dns)
DOMAIN=${DOMAIN}
EOF

echo "✓ .env file generated at $ENV_FILE"

