DO $$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'users_app') THEN
            EXECUTE format('CREATE USER users_app WITH PASSWORD %L', '{{APP_DB_PASSWORD}}');
        END IF;
    END $$;

GRANT CONNECT ON DATABASE users TO users_app;
GRANT USAGE ON SCHEMA public TO users_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO users_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO users_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO users_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO users_app;

ALTER TABLE users FORCE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_invitations FORCE ROW LEVEL SECURITY;
ALTER TABLE advertisers FORCE ROW LEVEL SECURITY;
ALTER TABLE advertiser_tenants FORCE ROW LEVEL SECURITY;