---
# Source: auth/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: auth
    app.kubernetes.io/version: "sha-55935b8c60d57dfc7ebc55229bb4425d5c35b849"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: auth-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com
