apiVersion: v2
name: locations
version: 0.1.0
description: Trip management service for trip-manager application
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../../charts/common"