---
# Source: presigner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presigner
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: presigner
    app.kubernetes.io/instance: presigner
    app.kubernetes.io/version: "dev"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: presigner
      app.kubernetes.io/instance: presigner
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: presigner
        app.kubernetes.io/instance: presigner
      annotations:
        checksum/config: 7e79973c3fc1fd52c92dbae71c6a31d495ddcaabfcaf878c0d25d4cc6f6c7ef8
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: presigner
          image: "europe-west1-docker.pkg.dev/project-32c60644-299b-4b05-8cf/trip-manager/backend/presigner:dev"
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
          env: 
            - name: PORT
              value: "8085"
            - name: LOG_LEVEL
              value: info
            - name: STORAGE_PROVIDER
              value: gcs
            - name: STORAGE_BUCKET
              value: trip-manager-bucket
            - name: AUTH_SERVICE_URL
              value: http://auth.trip-manager-prod.svc.cluster.local:8082
            - name: GCS_SIGNER_SA
              value: presigner-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com
            - name: CORS_ALLOWED_ORIGINS
              value: https://neatnode.xyz,https://www.neatnode.xyz
            - name: OTEL_COLLECTOR_ENDPOINT
              value: otel-collector.trip-manager-prod.svc.cluster.local:4317
          resources: 
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      serviceAccountName: presigner
