/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision internal user record for authenticated Firebase user
         * @description Creates an internal user record for a user that has authenticated with Firebase
         *     but does not yet exist in the application's database. Must be called after a
         *     successful Firebase sign-up or sign-in before any other authenticated API calls.
         *
         *     Idempotent: if the user already exists (matched by Firebase UID), the existing
         *     record is returned with 200 OK. If a new record is created, 201 Created is returned.
         *
         *     The request body is optional. If provided, fields override the values extracted
         *     from the Firebase token claims (e.g., to set a custom display name different
         *     from the one in the Firebase profile).
         */
        post: operations["provisionMe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/presigned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a presigned URL for direct file upload
         * @description Request a presigned URL to upload files directly to S3/MinIO without routing through the backend. Presigned URLs are valid for 15 minutes and can be used with PUT requests to upload files directly.
         */
        post: operations["getPresignedUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getMe"];
        /**
         * Update current user profile
         * @description Update user profile with profile information. To upload a profile avatar: (1) Request a presigned URL via POST /uploads/presigned, (2) upload the file directly to the presigned URL,
         */
        put: operations["updateMe"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all trips created by the current user */
        get: operations["listTrips"];
        put?: never;
        /** Create a new trip */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get trip details */
        get: operations["getTrip"];
        /** Update trip */
        put: operations["updateTrip"];
        post?: never;
        /** Delete trip */
        delete: operations["deleteTrip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trip locations */
        get: operations["listLocations"];
        put?: never;
        /** Add location to trip */
        post: operations["addLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/locations/{locationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update location */
        put: operations["updateLocation"];
        post?: never;
        /** Remove location from trip */
        delete: operations["deleteLocation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/locations/{locationId}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add image to location */
        post: operations["addLocationImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/locations/{locationId}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove image from location */
        delete: operations["deleteLocationImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trip activities */
        get: operations["listActivities"];
        put?: never;
        /** Add activity to trip */
        post: operations["addActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/activities/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update activity */
        put: operations["updateActivity"];
        post?: never;
        /** Delete activity */
        delete: operations["deleteActivity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/transports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trip transports */
        get: operations["listTransports"];
        put?: never;
        /** Add transport to trip */
        post: operations["addTransport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/transports/{transportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transport details */
        get: operations["getTransport"];
        /** Update transport */
        put: operations["updateTransport"];
        post?: never;
        /** Delete transport */
        delete: operations["deleteTransport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/accommodations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trip accommodations */
        get: operations["listAccommodations"];
        put?: never;
        /** Add accommodation to trip */
        post: operations["addAccommodation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/accommodations/{accommodationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update accommodation */
        put: operations["updateAccommodation"];
        post?: never;
        /** Delete accommodation */
        delete: operations["deleteAccommodation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get like count and like status for a trip */
        get: operations["getTripLikes"];
        put?: never;
        /** Like a trip */
        post: operations["likeTrip"];
        /** Unlike a trip */
        delete: operations["unlikeTrip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List comments for a trip */
        get: operations["listTripComments"];
        put?: never;
        /** Add a comment to a trip */
        post: operations["createTripComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a comment */
        delete: operations["deleteTripComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Read-only fields present on every persisted resource. Reused via allOf composition in all Response schemas. */
        ResourceMeta: {
            /** Format: uuid */
            readonly id: string;
            createdBy: components["schemas"]["UserSummary"];
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
        };
        /** @description Minimal user representation embedded in resource responses. */
        UserSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @description Optional S3/MinIO/GCP object key for user's avatar image */
            readonly avatarKey?: string;
            /** Format: uri */
            readonly avatarUrl?: string;
        };
        /** @description Pagination envelope reused by all list responses. Compose via allOf: add a 'data' property with the specific item array. */
        PaginationMeta: {
            /** @description Total number of items matching the query */
            total: number;
            /** @description Max items returned in this page */
            limit: number;
            /** @description Number of items skipped */
            offset: number;
        };
        ProvisionUserRequest: {
            name?: string | null;
        };
        /** @description Request for a presigned URL to upload files directly to S3/MinIO */
        PresignedURLRequest: {
            /**
             * @description Name of the file to upload (e.g., "avatar.jpg")
             * @example avatar.jpg
             */
            fileName: string;
            /**
             * @description Type of media being uploaded
             * @enum {string}
             */
            mediaType: "avatar" | "trip" | "location" | "activity";
        };
        /** @description Presigned URL response for direct file uploads */
        PresignedURLResponse: {
            /**
             * Format: uri
             * @description URL that can be used to upload the file directly to S3/MinIO
             * @example http://minio:9000/trip-manager/avatars/user-id.jpg?X-Amz-Algorithm=...
             */
            presignedUrl: string;
            /**
             * @description Presigned URL expiration time in seconds (typically 900 = 15 minutes)
             * @example 900
             */
            expiresIn: number;
            /** @description Object key to reference this upload in subsequent requests */
            key: string;
        };
        /** @description Full user object returned by profile endpoints. */
        UserResponse: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            name: string;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
            /** @description Optional user bio or profile description */
            bio?: string;
            /** @description Short-lived signed URL for avatar download */
            readonly avatarUrl?: string | null;
        };
        UpdateUserRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            /** @description Optional user bio or profile description */
            bio?: string;
            /** @description Optional S3/MinIO/GCP object key for user's avatar image */
            avatarKey?: string | null;
        };
        CreateTripRequest: {
            title: string;
            shortDescription: string;
            description?: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
        };
        UpdateTripRequest: {
            title?: string;
            shortDescription?: string;
            description?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            status?: "planned" | "ongoing" | "completed" | "cancelled";
        };
        /** @description Full trip object returned by all trip endpoints. */
        TripResponse: components["schemas"]["ResourceMeta"] & {
            title: string;
            shortDescription: string;
            description?: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @enum {string} */
            status: "planned" | "ongoing" | "completed" | "cancelled";
        };
        /** @description Paginated list of trips. */
        TripListResponse: components["schemas"]["PaginationMeta"] & {
            data: components["schemas"]["TripResponse"][];
        };
        CreateLocationRequest: {
            name: string;
            city: string;
            country: string;
            shortDescription: string;
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo: string;
            /** Format: float */
            latitude?: number;
            /** Format: float */
            longitude?: number;
            notes?: string;
            /** @description Visit sequence number */
            sequence?: number;
        };
        UpdateLocationRequest: {
            name?: string;
            city?: string;
            country?: string;
            shortDescription?: string;
            /** Format: date */
            dateFrom?: string;
            /** Format: date */
            dateTo?: string;
            /** Format: float */
            latitude?: number;
            /** Format: float */
            longitude?: number;
            notes?: string;
            sequence?: number;
        };
        /** @description Full location object returned by all location endpoints. */
        LocationResponse: components["schemas"]["ResourceMeta"] & {
            name: string;
            city: string;
            country: string;
            shortDescription: string;
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo: string;
            /** Format: float */
            latitude?: number;
            /** Format: float */
            longitude?: number;
            notes?: string;
            sequence?: number;
            readonly images?: components["schemas"]["LocationImageResponse"][];
        };
        /** @description Paginated list of locations. */
        LocationListResponse: components["schemas"]["PaginationMeta"] & {
            data: components["schemas"]["LocationResponse"][];
        };
        LocationImageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            locationId: string;
            /** Format: uri */
            imageUrl: string;
            sequence?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        AddLocationImageRequest: {
            /** @description S3/MinIO object key for the image */
            imageKey: string;
            sequence?: number;
        };
        CreateActivityRequest: {
            name: string;
            description?: string;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            /** Format: uuid */
            locationId: string;
            /** @enum {string} */
            category?: "sightseeing" | "dining" | "transport" | "accommodation" | "other";
            /** Format: float */
            cost?: number;
            /** @default USD */
            currency: string;
        };
        UpdateActivityRequest: {
            name?: string;
            description?: string;
            /** Format: date */
            date?: string;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            /** Format: uuid */
            locationId?: string;
            /** @enum {string} */
            category?: "sightseeing" | "dining" | "transport" | "accommodation" | "other";
            /** Format: float */
            cost?: number;
            currency?: string;
        };
        /** @description Full activity object returned by all activity endpoints. */
        ActivityResponse: components["schemas"]["ResourceMeta"] & {
            name: string;
            description?: string;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            /** Format: uuid */
            locationId: string;
            /** @enum {string} */
            category?: "sightseeing" | "dining" | "transport" | "accommodation" | "other";
            /** Format: float */
            cost?: number;
            currency?: string;
            /** @description Number of likes on this activity */
            readonly likeCount?: number;
            /** @description Number of comments on this activity */
            readonly commentCount?: number;
        };
        /** @description Paginated list of activities. */
        ActivityListResponse: components["schemas"]["PaginationMeta"] & {
            data: components["schemas"]["ActivityResponse"][];
        };
        CreateTransportRequest: {
            /** Format: uuid */
            fromLocationId: string;
            /** Format: uuid */
            toLocationId: string;
            /** Format: date-time */
            departureTime?: string;
            /** Format: date-time */
            arrivalTime?: string;
            /** @enum {string} */
            type: "flight" | "train" | "car" | "bus";
            notes?: string;
        };
        UpdateTransportRequest: {
            /** Format: uuid */
            fromLocationId?: string;
            /** Format: uuid */
            toLocationId?: string;
            /** Format: date-time */
            departureTime?: string;
            /** Format: date-time */
            arrivalTime?: string;
            /** @enum {string} */
            type?: "flight" | "train" | "car" | "bus";
            notes?: string;
        };
        /** @description Full transport object returned by all transport endpoints. */
        TransportResponse: components["schemas"]["ResourceMeta"] & {
            /** Format: uuid */
            fromLocationId: string;
            /** Format: uuid */
            toLocationId: string;
            /** Format: date-time */
            departureTime?: string;
            /** Format: date-time */
            arrivalTime?: string;
            /** @enum {string} */
            type: "flight" | "train" | "car" | "bus";
            notes?: string;
        };
        /** @description Paginated list of transports. */
        TransportListResponse: components["schemas"]["PaginationMeta"] & {
            data: components["schemas"]["TransportResponse"][];
        };
        CreateAccommodationRequest: {
            /** Format: uuid */
            locationId: string;
            name: string;
            address?: string;
            /** Format: date-time */
            checkIn?: string;
            /** Format: date-time */
            checkOut?: string;
            /** Format: float */
            pricePerNight?: number;
            notes?: string;
        };
        UpdateAccommodationRequest: {
            /** Format: uuid */
            locationId?: string;
            name?: string;
            address?: string;
            /** Format: date-time */
            checkIn?: string;
            /** Format: date-time */
            checkOut?: string;
            /** Format: float */
            pricePerNight?: number;
            notes?: string;
        };
        /** @description Full accommodation object returned by all accommodation endpoints. */
        AccommodationResponse: components["schemas"]["ResourceMeta"] & {
            /** Format: uuid */
            locationId: string;
            name: string;
            address?: string;
            /** Format: date-time */
            checkIn?: string;
            /** Format: date-time */
            checkOut?: string;
            /** Format: float */
            pricePerNight?: number;
            notes?: string;
        };
        /** @description Paginated list of accommodations. */
        AccommodationListResponse: components["schemas"]["PaginationMeta"] & {
            data: components["schemas"]["AccommodationResponse"][];
        };
        TripLikeResponse: {
            likeCount: number;
            hasLiked: boolean;
        };
        CreateTripCommentRequest: {
            text: string;
        };
        TripCommentResponse: {
            id: string;
            tripId: string;
            user: components["schemas"]["UserSummary"];
            text: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TripCommentListResponse: {
            data: components["schemas"]["TripCommentResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    provisionMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProvisionUserRequest"];
            };
        };
        responses: {
            /** @description User was already provisioned; existing record returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description User was newly provisioned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing or invalid Firebase token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPresignedUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignedURLRequest"];
            };
        };
        responses: {
            /** @description Presigned URL generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedURLResponse"];
                };
            };
            /** @description Invalid mediaType or missing required fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to generate presigned URL */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTrips: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of trips */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Trip created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden – trip belongs to another user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripRequest"];
            };
        };
        responses: {
            /** @description Trip updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listLocations: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationRequest"];
            };
        };
        responses: {
            /** @description Location added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationRequest"];
            };
        };
        responses: {
            /** @description Location updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Location not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Location not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addLocationImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddLocationImageRequest"];
            };
        };
        responses: {
            /** @description Image added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationImageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteLocationImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                locationId: string;
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Image not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listActivities: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of activities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityRequest"];
            };
        };
        responses: {
            /** @description Activity added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                activityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActivityRequest"];
            };
        };
        responses: {
            /** @description Activity updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Activity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                activityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Activity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTransports: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of transports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransportRequest"];
            };
        };
        responses: {
            /** @description Transport added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                transportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transport details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transport not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                transportId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransportRequest"];
            };
        };
        responses: {
            /** @description Transport updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transport not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                transportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transport deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transport not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAccommodations: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of accommodations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccommodationListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addAccommodation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccommodationRequest"];
            };
        };
        responses: {
            /** @description Accommodation added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccommodationResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAccommodation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                accommodationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccommodationRequest"];
            };
        };
        responses: {
            /** @description Accommodation updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccommodationResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Accommodation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAccommodation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                accommodationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accommodation deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Accommodation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTripLikes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Like info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripLikeResponse"];
                };
            };
        };
    };
    likeTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip liked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already liked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unlikeTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip unliked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTripComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripCommentListResponse"];
                };
            };
        };
    };
    createTripComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripCommentRequest"];
            };
        };
        responses: {
            /** @description Comment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripCommentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteTripComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
