image:
  registry: docker.io
  repository: neo4j
  tag: 5.19-community

auth:
  enabled: true
  password: "neo4jpassword"  # wird in prod überschrieben

plugins:
  - apoc

config:
  dbms.security.procedures.unrestricted: "apoc.*"

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

persistence:
  enabled: true
  size: 8Gi