ingress:
  enabled: true
  className: nginx
  host: ""

routes:
  auth:
    service: auth
    port: 8082
    path: /api/auth
  presigner:
    service: presigner
    port: 8085
    path: /api/presign
  social:
    service: social
    port: 8081
    path: /api/social
  users:
    service: users
    port: 8083
    path: /api/users
  trips:
    service: trips
    port: 8084
    path: /api/trips
  frontend:
    service: frontend
    port: 3000
    path: /