ingress:
  enabled: true
  className: nginx
  host: ""

routes:
  social:
    service: social
    port: 8081
    path: /api/social
    healthPath: /health
  auth:
    service: auth
    port: 8082
    path: /api/auth
    healthPath: /health
  users:
    service: users
    port: 8083
    path: /api/users
    healthPath: /health
  trips:
    service: trips
    port: 8084
    path: /api/trips
    healthPath: /health
  travelInfo:
    service: travel-info
    port: 8087
    path: /api/info
    healthPath: /health
  feed:
    service: feed
    port: 8089
    path: /api/feed
    healthPath: /health
  newsletter:
    service: newsletter
    port: 8070
    path: /api/newsletter
    healthPath: /health
  tenants:
    service: users
    port: 8083
    path: /api/tenants
    healthPath: /health


  frontend:
    service: frontend
    port: 3000
    path: /