ingress:
  enabled: true
  className: nginx
  host: ""

routes:
  social:
    service: social
    port: 8081
    path: /api/social
  auth:
    service: auth
    port: 8082
    path: /api/auth
  users:
    service: users
    port: 8083
    path: /api/users
  trips:
    service: trips
    port: 8084
    path: /api/trips
  presigner:
    service: presigner
    port: 8085
    path: /api/presign
  locations:
    service: locations
    port: 8086
    path: /api/locations
  travelWarning:
    service: travel-warning
    port: 8087
    path: /api/warnings
  weatherInfo:
    service: weather-info
    port: 8088
    path: /api/weather



  frontend:
    service: frontend
    port: 3000
    path: /