neo4j:
  enabled: true
env:
  - name: _NEO4J_PASS
    value: "neo4jpassword"
  - name: NEO4J_AUTH
    value: "neo4j/$(_NEO4J_PASS)"
  - name: NEO4J_PLUGINS
    value: '["apoc"]'
  - name: NEO4J_dbms_security_procedures_unrestricted
    value: "apoc.*"

devPassword: "neo4jpassword"

externalSecrets:
  enabled: false

storage: 8Gi