neo4j:
  enabled: true
env:
  - name: _NEO4J_PASS
    valueFrom:
      secretKeyRef:
        name: neo4j-secret
        key: NEO4J_PASSWORD
  - name: NEO4J_AUTH
    value: "neo4j/$(_NEO4J_PASS)"
  - name: NEO4J_PLUGINS
    value: '["apoc"]'
  - name: NEO4J_dbms_security_procedures_unrestricted
    value: "apoc.*"

externalSecrets:
  enabled: true

storage: 8Gi