redis:
  auth:
    enabled: true
    existingSecret: neo4j-secret
    existingSecretPasswordKey: NEO4J_PASSWORD
  master:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi