replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

hpa:
  enabled: false

env:
  - name: PORT
    value: "8081"
  - name: LOG_LEVEL
    value: "debug"
  - name: FIRESTORE_PROJECT_ID
    value: "trip-manager-local"
  - name: FIRESTORE_EMULATOR_HOST
    value: "firebase-emulator.trip-manager-dev.svc.cluster.local:8080"
  - name: AUTH_CLIENT_CONNECTION_STRING
    value: "http://auth.trip-manager-dev.svc.cluster.local:8082"
  - name: USERS_SERVICE_URL
    value: "http://users.trip-manager-dev.svc.cluster.local:8083"
  - name: GCP_PROJECT_ID
    value: "trip-manager-local"
  - name: PUBSUB_TOPIC_ID
    value: "trip-events"
  - name: PUBSUB_EMULATOR_HOST
    value: "pubsub-emulator.trip-manager-dev.svc.cluster.local:8085"
  - name: CORS_ALLOWED_ORIGINS
    value: "http://localhost:3000"