image:
  repository: ""
  tag: ""

service:
  port: 8090

probes:
  liveness: /health
  readiness: /health

replicaCount: 1

hpa:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  - name: PORT
    value: "8090"
  - name: GCP_PROJECT_ID
    value: "project-32c60644-299b-4b05-8cf"
  - name: PUBSUB_SUBSCRIPTION_ID
    value: "feed-generator-trip-created,feed-generator-trip-liked,feed-generator-trip-commented"
  - name: LOG_LEVEL
    value: "info"

envFrom: []

externalSecrets:
  enabled: false
  secrets: []

serviceAccount:
  gcpServiceAccount: ""